version: "3.9"

services:
  backend:
    build:
      context: .
    # Elegimos el Dockerfile del backend
    dockerfile: backend/Dockerfile
    env_file:
      - .env
    expose:
      - "8000"
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    depends_on:
      - backend
    ports:
      - "8097:80"
    restart: unless-stopped
